site:
  title: My Software Artifacts Documentation
  start_page: software-artifact-1::index.adoc
content:
  sources:
    - url: https://github.com/ltsallas/software-artifact-demo
      start_path: docs
      branches: [main]
      edit_url: true
    - url: https://github.com/ltsallas/software-artifact-2
      start_path: docs
      branches: [ main ]
      edit_url: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    kroki-fetch-diagram: true
    page-pagination: true
  extensions:
      - asciidoctor-kroki
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
    - require: asciidoctor-kroki
